{% set version = "1.0.0" %}

package:
  name: yacht
  version: {{ version }}

source:
  url: <put url here>
  sha256: <put sha here>

build:
  number: 0
  noarch: generic
  run_exports:
    - {{ pin_subpackage('yacht', max_pin="x") }}

requirements:
  host:
    - python >3.6
    - pip
  run:
    - python >3.6
    - sourmash >=4.8.3,<5
    - rust
    - scipy
    - numpy
    - pandas
    - scikit-learn
    - loguru
    - maturin >=1,<2
    - tqdm
    - biom-format
    - pytaxonkit
    - openpyxl

test:
  imports:
    - yacht

  commands:
    - yacht --help

about:
  home: https://github.com/KoslickiLab/YACHT
  summary: 'YACHT is a mathematically rigorous hypothesis test for the presence or absence of organisms in a metagenomic sample, based on average nucleotide identity (ANI).'
  license: MIT License
  license_file: LICENSE.txt
  dev_url: https://github.com/KoslickiLab/YACHT
  doc_url: https://github.com/KoslickiLab/YACHT/wiki

extra:
  identifiers:
    - doi:10.1101/2023.04.18.537298
  recipe-maintainers:
    - dkoslicki
  authors:
    - dkoslicki
    - chunyuma
    - sew347
    - mlupei
    - mfl15
    - ShaopengLiu1
    - raquellewei
    - mohsenht
